site_name: Welcome to ILKE Docs
site_url: https://github.com/ilkilabs/ilke
repo_url: https://github.com/pierreilki/documentation
repo_name: GitHub
edit_uri: https://github.com/pierreilki/documentation/tree/master/docs
site_description: This site provide a full documentation of ILKE Kubernetes Distribution.
copyright: Copyright  &#169; 2021  <a href="https://www.ilki.fr/">ILKI - ILKILABS</a>
nav:
    - ILKE: index.md
    - User Guide:
        - Quickstart: main/main.md
        - Instructions: main/instructions.md
        - Configuration: main/configurations.md
        - Parameters: main/parameters.md
        - Manage ETCD: main/etcd_management.md
    - Tutorials:
        - Deploy ILKE VirtualBox: tutorials/deploy_agorakube.md
    - About:
#       - Release Notes: about/release-notes.md
        - Contributing: about/contributing.md
        - License: about/license.md
theme:
    name: readthedocs
    custom_dir: custom_theme/ 
plugins:
    - search
#    - git-revision-date-localized
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
extra:
  social:
    - type: 'github'
      link: 'https://github.com/ilkilabs/ilke'
    - type: 'twitter'
      link: 'https://twitter.com/ClouDesigner'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/ilki'
